language: node_js
node_js:
  - "9.4"
cache:
  directories:
  - "node_modules"
env:
  global:
  - CC_TEST_REPORTER_ID=ca886e39a90dcda3a681d64e9700d922034579465f249463c653d016b7294944

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm test
- npm run coverage
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
